### ISSUE TITLE
Release for Scala 2.10.7 and 2.11.12

### ISSUE THREAD

**Issue by ruippeixotog** [scalamacros/paradise#108]
cc @xeno-by

**Comment by xeno-by** [comment]
Have these Scala versions been officially released?

**Comment by ruippeixotog** [comment]
My bad... I thought they were released together with Scala 2.12.4 because of [this comment](https://github.com/scala/scala-dev/issues/432#issuecomment-337302356), but it seems that they aren't yet on Maven. https://github.com/scala/scala-dev/issues/434 and https://github.com/scala/scala-dev/issues/433 are still open, too.
 
Feel free to close this until those versions are released or leave this open for that time.

**Comment by xeno-by** [comment]
Let's keep this ticket open. Can you please ping me once 2.10.7 and 2.11.12 are released?

**Comment by ruippeixotog** [comment]
Sure!

**Comment by adriaanm** [comment]
🔔

**Comment by xeno-by** [comment]
:heart:

**Comment by xeno-by** [comment]
Released.
