### ISSUE TITLE
quasiquotes 2.1.1 not published for 2.10.7?

### ISSUE THREAD

**Issue by milessabin** [scalamacros/paradise#111]
It looks like the POM for paradise_2.10 2.1.1 is expecting quasiquotes 2.1.1, but the latter doesn't appear to be available on central.

**Comment by xeno-by** [comment]
No idea how this could've fallen through the cracks. Now fixed: https://oss.sonatype.org/content/repositories/releases/org/scalamacros/quasiquotes_2.10/2.1.1/.

**Comment by milessabin** [comment]
Thanks!

**Comment by gabrieljones** [comment]
There is an error message that might need fixing as well:

`Quasiquotes in macro paradise for Scala 2.10 require a dependency on a supporting library. Add the following line to your SBT build: libraryDependencies += "org.scalamacros" %% "quasiquotes" % "2.1.0-SNAPSHOT"`

should probably read:

`Quasiquotes in macro paradise for Scala 2.10 require a dependency on a supporting library. Add the following line to your SBT build: libraryDependencies += "org.scalamacros" %% "quasiquotes" % "2.1.1"`

**Comment by xeno-by** [comment]
Oops. I'll try to remember to fix this in the next release!
