### ISSUE TITLE
2.13 compat: bridgeAnnot is gone

### ISSUE THREAD

**Issue by SethTisue** [scalamacros/paradise#114]
seen in Scala 2.13 community build at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/991/consoleFull since https://github.com/scala/scala/pull/6319 was merged:

```
[macro-paradise] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.11/project-builds/macro-paradise-df77405a1f4a9dd7806f923661f9fb7a3fbfcbb2/plugin/src/main/scala/org/scalamacros/paradise/typechecker/Namers.scala:278: value bridgeAnnot is not a member of object Namers.this.global.tpnme
[macro-paradise] [error]           val bridgeFlag = if (mods hasAnnotationNamed tpnme.bridgeAnnot) BRIDGE | ARTIFACT else 0
```

**Comment by NthPortal** [comment]
#113 hopefully fixes this

**Comment by xeno-by** [comment]
@NthPortal Thanks for the pull request! I'll do my best to review it this week. If this is more urgent than "sometime this week", please let me know, and I'll try extra hard to find time.
