### ISSUE TITLE
2.12.6

### ISSUE THREAD

**Issue by zy4** [scalamacros/paradise#116]
`[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalamacros#paradise_2.12.6;2.1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] `

**Comment by coltfred** [comment]
This is indeed a blocker for many projects. I know @rossabaker is blocked for http4s. Anything that uses Simulacrum is also blocked (meaning most of the typelevel builds).

**Comment by adriaanm** [comment]
2.1.0 for 2.12.6 is available via resolver https://oss.sonatype.org/content/repositories/staging/ -- since this is my first time releasing this project, would be good to hear if it works before releasing to maven central

**Comment by adriaanm** [comment]
I saw there's also a 2.1.1 for 2.12.5, so I'm not sure if this is right

**Comment by adriaanm** [comment]
I checked the bytecode for 2.1.0 and 2.1.1 on 2.12.5, and there's no difference as far as I can see

**Comment by fthomas** [comment]
@adriaanm It works for me: https://github.com/fthomas/refined/pull/490

**Comment by adriaanm** [comment]
Thanks! Promoting :-)

**Comment by zy4** [comment]
Works for me too. Can be closed now!
