### ISSUE TITLE
Release for 2.13.0-M4

### ISSUE THREAD

**Issue by marcospereira** [scalamacros/paradise#118]

**Comment by xuwei-k** [comment]
- https://github.com/scala/scala/pull/6606
- https://github.com/milessabin/macro-compat/commit/b1bbe40105a649abf35511fe8e7de4c0419192f7#diff-04c6e90faac2675aa89e2176d2eec7d8R115

**Comment by SethTisue** [comment]
this ticket should be closed. as of Scala 2.13.0-M4, macro paradise is part of the compiler, enabled with `-Ymacro-annotations`

**Comment by xeno-by** [comment]
@SethTisue I've added you to admins of the repository. Please feel free to open/close tickets, create branches, etc.
