### ISSUE TITLE
consider duplicating annotation expansions

### ISSUE THREAD

**Issue by xeno-by** [scalamacros/paradise#12]

**Comment by aparo** [comment]
May you expand the issue description?

Thanks

**Comment by xeno-by** [comment]
It's a follow-up for https://github.com/scala/scala/pull/3257 and https://github.com/scala/scala/pull/3292. 

Since trees are mutable, we have to be extra careful to avoid sharing them around, because otherwise a mutation from some faraway place in the code might end up hitting us unexpectedly. A proper solution would be rearchitecturing the compiler so that trees are immutable, but deep copying on enters/exits of our APIs (also known as duplicating in scalac parlance) is the cheapest way to sidestep this problem.

**Comment by xeno-by** [comment]
It looks like non-duplication doesn't lead to any significant problems. We may consider reopening this issue if it will.
