### ISSUE TITLE
Publish for 2.12.9

### ISSUE THREAD

**Issue by eatkins** [scalamacros/paradise#120]
I know this isn't maintained anymore, but if it isn't too much work, I think it should be published for 2.12.9.

**Comment by SethTisue** [comment]
@adriaanm this goes on your plate, I think?

@eatkins while you're waiting, you might try just using the 2.12.8 one and see if it works on 2.12.9 as well. (perhaps none of the compiler internals changes we made actually affected paradise.)

**Comment by eed3si9n** [comment]
I've pinged Adriaan earlier, so this should happen within a day or two.

**Comment by regadas** [comment]
tested `paradise` `2.12.8` with `2.12.9` on [spotify/scio](https://github.com/spotify/scio) and it seems ok! 👍

**Comment by adriaanm** [comment]
Now available on [maven central](http://central.maven.org/maven2/org/scalamacros/paradise_2.12.9/). https://github.com/scalamacros/paradise/releases/tag/v2.1.0_2.12.9
