### ISSUE TITLE
Publish for Scala 2.12.10

### ISSUE THREAD

**Issue by exoego** [scalamacros/paradise#121]
[Scala 2.12.10 is out there](https://github.com/scala/scala/releases/tag/v2.12.10).
Assuming macroparadise is maintained for Scala 2.12.x.
Thanks in advance.

**Comment by SethTisue** [comment]
this is @adriaanm's wheelhouse

**Comment by adriaanm** [comment]
Yep will do today.

**Comment by olafurpg** [comment]
Close ticket? Artifacts seem to be on Maven already, thanks!

```
coursier fetch org.scalamacros:paradise_2.12.10:2.1.1
```

**Comment by exoego** [comment]
Thanks!!
Closing since released.

**Comment by adriaanm** [comment]
👍
