### ISSUE TITLE
c.typeCheck doesn't see declarations from the current scope

### ISSUE THREAD

**Issue by xeno-by** [scalamacros/paradise#14]
A very thorough discussion: https://github.com/aztek/scala-workflow/issues/2

Related SO questions: http://stackoverflow.com/questions/19379436/cant-access-parents-members-while-dealing-with-macro-annotations and http://stackoverflow.com/questions/19954776/scala-macro-annotations-c-typecheck-of-annotated-type-causes-stackoverflowerror

**Comment by xeno-by** [comment]
There's an interesting twist to this story. If one tries to typecheck something that refers to the type parameters of the annottee, these type parameters wouldn't be taken into account: https://github.com/aztek/scala-workflow/issues/2#issuecomment-31295373

**Comment by FlorianKirmaier** [comment]
since 2.0.0-M8 the situation is worse. The compiler crashes with the following error:
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object TNodeASDF

Here is a example: http://pastebin.com/raw.php?i=Svm11P10

**Comment by aparo** [comment]
@FlorianKirmaier you are using java 1.8.0-ea. How is it stable?
Kudos to you of using 2.11-M8 on Java 1.8.0-ea :-)

**Comment by xeno-by** [comment]
Thank you! I'll try to take a look today.

**Comment by xeno-by** [comment]
@aparo Yeah, I can reproduce the error. I'll see what I can do.

**Comment by xeno-by** [comment]
@FlorianKirmaier I get the same error in the most recent paradise for M7. When did it stop working for you?

**Comment by xeno-by** [comment]
I see now. This problem is a direct consequence of the fix I applied above. It only manifests itself when there's an import in scope, which is why I missed it in the first place.

**Comment by xeno-by** [comment]
@FlorianKirmaier @aparo Fixed the regression, started jenkins builds. The fix should be published with an updated 2.0.0-SNAPSHOT build for all supported Scala versions (2.10.3, 2.10.4-SNAPSHOT, 2.11.0-M7, 2.11.0-M8, 2.11.0-SNAPSHOT) within a couple hours.

**Comment by xeno-by** [comment]
Unfortunately I haven't made any progress here, so we won't have a fix in 2.0.0-final. Any ideas are very welcome!

**Comment by xeno-by** [comment]
I've merged this issue into https://github.com/scalamacros/paradise/issues/75 and will close this issue now. If this is a blocker for you, please let me know, and we'll think of something.
