### ISSUE TITLE
repl doesn't see new definitions synthesized by macro expansions

### ISSUE THREAD

**Issue by xeno-by** [scalamacros/paradise#19]
That's because MemberHandlers don't communicate with the compiler about the code that it compiles user input into, but rather try to guess what definitions will be introduced by parsing user input. No idea how hard this will be to fix.

**Comment by xeno-by** [comment]
Also needs to work with SBT

**Comment by xeno-by** [comment]
Fixed in 5a10b96815

**Comment by som-snytt** [comment]
That was interesting.

**Comment by xeno-by** [comment]
@som-snytt No idea whether that's the best approach. Just something that I had to quickly hack up. I've seen Paul's comment that suggests he wanted to use trees after typechecking, but left that for future work. Maybe you happen to know details?

**Comment by som-snytt** [comment]
My prototype repl using a "scripter" phase would collect trees at the end of the pipeline, as a followup to that comment.  Maybe I'll try to get back to it during the RC interregnum. The idea was the scripter is pluggable, so repl just waits to see what sausage is produced.
