### ISSUE TITLE
Macro annotations with explicitly provided type arguments don't expand

### ISSUE THREAD

**Issue by xeno-by** [scalamacros/paradise#2]
https://github.com/aztek/scala-workflow/issues/2#issuecomment-23592994

**Comment by stanch** [comment]
@xeno-by, this seems to work for me, but looking how complex everything around is, maybe you should do a sanity check :)

**Comment by stanch** [comment]
The tests pass, however in console:

``` scala
scala> @shove[Double] val superpower = 41.999
<console>:5: error: value superpower is not a member of object $iw
  lazy val $result = `superpower`
                                                   ^
<console>:10: error: value superpower is not a member of object $iw
 + "superpower: <notype> = " + scala.runtime.ScalaRunTime.replStringOf(`superpower`, 1000)
                                                                                                     ^
```

Hmmm?

**Comment by xeno-by** [comment]
Macro annotations never worked in repl.

**Comment by stanch** [comment]
Am I spoiled?

``` scala
[info] Starting scala interpreter...
[info]
import workflow._
import Shortcuts._
Welcome to Scala version 2.10.3-RC1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> @opt val x = Some(4) * 2 - Some(5)
x: Option[Int] = Some(3)
```

**Comment by xeno-by** [comment]
I mean they will expand just fine, but it's that newly generated members won't be found by repl, and I'm not yet sure how to remedy that.

**Comment by xeno-by** [comment]
Btw do you have an actual pull request? Can't find anything to merge. This is just an issue discussion, not a pull request discussion.

**Comment by stanch** [comment]
> Btw do you have an actual pull request? Can't find anything to merge. This is just an issue discussion, not a pull request discussion.

Sure, I’ll submit one now. Just wanted to make sure that the REPL thing is not something extraordinary before that.

**Comment by stanch** [comment]
I think we can close this now :)
