### ISSUE TITLE
Liftable[Tree]

### ISSUE THREAD

**Issue by stanch** [scalamacros/paradise#21]
I’m on `2.10`, paradise `M4` (soon to be `M5`). I would like to unquote `List[Tree]`. However it looks like either there is no `Liftable[Tree]`, or some path-dependent magic stops it from happening. I guess in the former case the solution is easy. If it’s because of the latter, maybe some evidence-based trickery would help? Like `implicit evidence: A =:= u.Tree`.

**Comment by stanch** [comment]
P.S. This works for me:

``` scala
implicit val `Tree is liftable` = Liftable[Tree](identity)
```

**Comment by xeno-by** [comment]
Could you provide a use case? /cc @densh

**Comment by stanch** [comment]
Sure. Consider this simple structure:

``` scala
case class Node(children: List[Node])
```

Suppose we are writing a compile-time string interpolator, that builds a `Node`:

``` scala
// this
val x: Node = ...
val y: Node = ...
val z: Node = node"Some text and $x and $y"

// compiles to this
val x: Node = ...
val y: Node = ...
val z: Node = Node(List(StringNode("Some text and "), x, StringNode(" and "), y))
```

When building this with quasiquotes, we need to unquote

``` scala
List(q"""StringNode("Some text and ")""", args(0).tree, q"""StringNode(" and ")""", args(1).tree)
```

which is a `List[Universe#Tree]`.

Now, `List[A]` is `Liftable` if `A` is `Liftable`. However, looking at the sources, there is no `Liftable[Tree]`, maybe because one can unquote it anyway. But the lack of a typeclass instance breaks generalization over collections.

**Comment by densh** [comment]
I've suggested having identity liftable for `Tree` too but @xeno-by wasn't sure if it's the right way to do it.

https://issues.scala-lang.org/browse/SI-8200

**Comment by xeno-by** [comment]
I suggest we move this discussion to the aforementioned JIRA issue.

**Comment by densh** [comment]
@stanch thanks for feedback, here is pull request to master to add suggested Liftable: https://github.com/scala/scala/pull/3653.

**Comment by densh** [comment]
By the way recommended way to do this if that pr doesn't get in is:

```
implicit def liftTree[T <: Tree]: Liftable[T] = Liftable { identity }
```

`Liftable[Tree]` won't work if you have more specific type like `ClassDef` due to the fact that `Liftable` is invariant in its type argument.

**Comment by stanch** [comment]
For the record, here’s a motivation for this choice that I wrote while on a train. Wanted to post to JIRA, but then I need to sign up, etc. And you’ve already gone ahead anyway.

> I would start by outlining the underlying consistency models (i.e., what “lifting” means) for the two approaches. Let us define  the reification chain as
> `X`, `reify { X }`, `reify { reify { X } }`, ...
> In option B “lifting” means always going one level down the chain:
> `1` → `q"1"`
> `Literal(Constant(1))` → `q"Literal(Constant(1))"`
> In option A “lifting” means going down as few levels as needed (0 or 1) to get a Tree:
> `1` → `q"1"`
> `Literal(Constant(1))` →  `q"1"`
> Now, I can see the approach B being somewhat simpler to grasp. However, I think we all agree that the approach A is much more practical. It also goes in line with the term “lifting”: we are pulling things to the same level. So I would definitely prefer this. Note that “going one level down” could be implemented in a separate method, or even separate typeclass, `Reifiable`.
