### ISSUE TITLE
M4/2.10 quasiquotes fail at runtime

### ISSUE THREAD

**Issue by stanch** [scalamacros/paradise#22]
Just to track [this](https://groups.google.com/d/msg/scala-language/BM1EPrZY3Hk/QwDmZ4Aj9l4J):

```
exception during macro expansion: 
[error] java.lang.ClassNotFoundException: scala.reflect.api.Universe$Liftable
```

**Comment by xeno-by** [comment]
Fixed in 46cd0f96c1, will soon be deployed in 2.0.0-M5.

**Comment by stanch** [comment]
Updated, now getting

```
exception during macro expansion: 
[error] java.lang.UnsupportedClassVersionError: scala/reflect/api/Universe$Liftable : Unsupported major.minor version 51.0
```

Maybe this is something on my side? The code is here: https://github.com/stanch/scalatags-md. Happens when you run `sbt test`.

**Comment by stanch** [comment]
> It's fascinating how many facets fail can have! This one is caused by Java-compiled portions of quasiquotes.jar being compiled with Java 7 :)
> 
> Would it be possible for you to use Java 7 or 8? I'd prefer to cool down the pace of releases if that's not an absolute blocker for you. Alternatively I could publish a snapshot build with Java 6.

A snapshot would be very nice :) There is a benefit for you as well in that I would (or wouldn’t) confirm that there are no more hidden surprises left :)

**Comment by stanch** [comment]
Just FYI, http://scalamacros.org/news/2014/03/23/macro-paradise-2.0.0-M4.html does not display the layout for some reason...

**Comment by xeno-by** [comment]
Thanks, fixed the layout and published `2.0.0-SNAPSHOT` against all supported branches.

**Comment by xeno-by** [comment]
If everything ends up working for you, I will publish `2.0.0-M6` one of these days.

**Comment by xeno-by** [comment]
Also, thanks a lot for testing things out!

**Comment by stanch** [comment]
You are welcome! But...

```
exception during macro expansion: 
[error] java.lang.NoSuchMethodError: scala.quasiquotes.StandardLiftables.Liftable()Lscala/quasiquotes/StandardLiftables$Liftable$;
[error]     at scala.quasiquotes.StandardLiftables$class.liftList(StandardLiftables.scala:54)
[...]
```

:D

**Comment by xeno-by** [comment]
That's a different error, which makes me kind of happy :)

How do I reproduce it?

**Comment by stanch** [comment]
You can clone https://github.com/stanch/scalatags-md and run `sbt test`. I’m on Java 6, as you already know. Old snapshots in Ivy cache cleaned.

**Comment by xeno-by** [comment]
Okay, thanks! These days I will be very occupied by EPFL stuff, but I'll do my best to take a look.

**Comment by stanch** [comment]
Thanks! I will not _really_ need this until next week, when I’m going to prepare _Macroid 2.0_ documentation.
Perhaps the issue should be reopened?

**Comment by holograph** [comment]
Another reproduction scenario: https://github.com/wix/accord/tree/paradise-2.0.x

**Comment by xeno-by** [comment]
Minimal reproduction:

```
import scala.reflect.macros.Context
import scala.language.experimental.macros
import scala.quasiquotes.StandardLiftables

class Helper[C <: Context](val c: C) extends StandardLiftables {
  import c.universe._
  val u: c.universe.type = c.universe

  val tpe = typeOf[Int]
  def bar = q"2: $tpe"
}

object Macros {
  def impl(c: Context) = {
    val helper = new Helper[c.type](c)
    c.Expr[Int](helper.bar)
  }

  def foo: Int = macro impl
}
```

```
object Test extends App {
  Macros.foo
}
```

**Comment by xeno-by** [comment]
Allright nailed it: https://github.com/scalamacros/paradise/commit/7dfce72cd3e2d4fc3caddc527bc096ff2d4dd6e0. Could you guys redownload the snapshot and try again?

**Comment by stanch** [comment]
Confirmed, thanks a lot!

**Comment by holograph** [comment]
M6 confirmed to work, thanks!
