### ISSUE TITLE
Error message about mismatch of identical expression when trying to return structural types with macroses defined in.

### ISSUE THREAD

**Issue by rssh** [scalamacros/paradise#4]
Next set of macro definitions:
https://github.com/rssh/scala-training-materials/blob/master/macro-experimental/misc/bugElProviderMin/src/main/scala/x/X.scala

When try to using one as specified in:
https://github.com/rssh/scala-training-materials/blob/master/macro-experimental/misc/bugElProviderMin/src/test/scala/tieSpec.scala

We see error message:
[error] /home/rssh/work/scala-training-materials/macro-experimental/misc/bugElProviderMin/src/test/scala/tieSpec.scala:11: macro implementation has wrong shape:
[error]  required: (c: scala.reflect.macros.Context)(ch: c.Expr[x.Channel[A]]): c.Expr[c.universe.Block]
[error]  found   : (c: scala.reflect.macros.Context)(ch: c.Expr[x.Channel[A]]): c.Expr[c.universe.Block]
[error] type mismatch for return type: c.Expr[c.universe.Block] does not conform to c.Expr[c.universe.Block]

As ypu can see, required and found parts are identical.

In worst case - we need to clarify error message. 

Full testable example is available at https://github.com/rssh/scala-training-materials/tree/master/macro-experimental/misc/bugElProviderMin

sbt test:compile to reproduce

**Comment by xeno-by** [comment]
Can reproduce the problem. Looking into it.

**Comment by xeno-by** [comment]
Is reification of rtree in readingImpl intended?

**Comment by xeno-by** [comment]
https://issues.scala-lang.org/browse/SI-7842

**Comment by rssh** [comment]
Ohh, this is other issue.  [I guess yet one error in compiler]: when change reify to c.Expr I receive

[error] /home/rssh/work/scala-training-materials/macro-experimental/misc/bugElProviderMin/src/test/scala/tieSpec.scala:11: type mismatch;
[error]  found   : H0
[error]  required: Nothing
[error]     val tie = makeTie
[error]               ^

So, to put minimal compiled example I just put reify.

**Comment by xeno-by** [comment]
c.Expr means c.Expr[Nothing]. Could you try providing a meaningful type?

**Comment by rssh** [comment]
Hmm, I guess static type must be deduced.
See: http://stackoverflow.com/questions/14370842/getting-a-structural-type-with-an-anonymous-classs-methods-from-a-macro?rq=1
Type is deduced there.
I try to do something simular (with macrodefinition inside)

**Comment by xeno-by** [comment]
Well, then write c.Expr[Any]

**Comment by xeno-by** [comment]
And don't forget {} in `new H1 {}`.

**Comment by rssh** [comment]
Wau !  with new H0 { }  instead new H0  it's works as expexted.  Thanks !

**Comment by xeno-by** [comment]
Cool!
