### ISSUE TITLE
c.typecheck causes spurious cyclic errors when used in a method annotation

### ISSUE THREAD

**Issue by xeno-by** [scalamacros/paradise#49]
https://twitter.com/copumpkin/status/482748250374832129

**Comment by xeno-by** [comment]
I've merged this issue into https://github.com/scalamacros/paradise/issues/75 and will close this issue now. If this is a blocker for you, please let me know, and we'll think of something.

**Comment by ClaireNeveu** [comment]
Is there any workaround for this? We have encountered this spurious `illegal cyclic reference involving class <className>` when annotating objects inside a class with our [Safe Config](https://github.com/gawkermedia/safe-config) macro.
