### ISSUE TITLE
Macro annotations don't expand on types

### ISSUE THREAD

**Issue by densh** [scalamacros/paradise#54]
It would be amazing to have macro annotations expand on types

``` scala
val rec: Rec@has(x: Int) = Rec(x = 42)
```

**Comment by xeno-by** [comment]
For a workaround, https://twitter.com/xeno_by/status/497789999824519168

**Comment by xeno-by** [comment]
Same as with https://github.com/scalamacros/paradise/issues/16, we will consider this for our new iteration of macros that will be coming with Dotty.
