### ISSUE TITLE
missleading error message (cyclic reference) with Macro-Annotations when typecheck doesn't work in the given context

### ISSUE THREAD

**Issue by FlorianKirmaier** [scalamacros/paradise#57]
```
class TestTypecheck() extends StaticAnnotation {
    def macroTransform(annottees: Any*): Any = macro Predef.TestTypecheckImpl
  }
  def TestTypecheckImpl(c: whitebox.Context)(annottees: c.Tree*): c.Tree = {
    import c._
    import universe._

    //try {
    c.typecheck(q"val a: Int")
    //} catch {
    //  case e => e.printStackTrace
    //}
    annottees(0)
  }
```

`object A2 { @TestTypecheck class B }`

This doesn't compile, because we can't have undeclareds member inside of an object.

When we don't catch the Exception, we get an cyclic reference error and a StackTrace which doesn't lead to the cause. This is really ugly to debug.
When we print the exception of typecheck, we can at least find our code in the Stacktrace.

An error message like the following would be great:
scala.reflect.macros.TypecheckException: only classes can have declared but undefined members

A variation of this is probably the cause of the error message in #49.
https://github.com/scalamacros/paradise/issues/49

**Comment by xeno-by** [comment]
Thanks for reporting! I'll see what I can do. In the meanwhile, is this a blocker for you?

**Comment by FlorianKirmaier** [comment]
This is not a blocker for me. It was only annoying to debug.
A simple way to improve the the userexperience could be, to log all exception, which are thrown inside of macros.

**Comment by xeno-by** [comment]
I've merged this issue into https://github.com/scalamacros/paradise/issues/75 and will close this issue now. If this is a blocker for you, please let me know, and we'll think of something.
