### ISSUE TITLE
Injecting Bindings, Code, Staging

### ISSUE THREAD

**Issue by sirinath** [scalamacros/paradise#58]
I hope all is well at your end. I am looking for the following functionality in Macro Paradise plugin.

``` Scala
var name111 = ...
var name222 = ...

var q0 = q" ... $${} ... "

var q1 = q".... $$name" bindStatic("name", q"$name111") // compile time binds which replace $$name with $name111
var q2 = q".... var a : $$t = ..." bindDynamic("t", Tree.from("MyType")) // runtime time binds injection like dependency injection. In this case MyType is injected in place of $$t
var q3 = q".... $${} ..." bindStatic(0, q" ... ") // Inject some code at compile time
var q4 = q".... $${} ..." bindDynamic(0, q" ... ") // Inject some code at run time
var q5 = q0 bindStatic(0, q" .... ") // Rebind into new tree
var q6 = q1 bindStatic("name", q"$name222") // Rebind into new tree
```

Binding are static or dynamic and can be for variables, types and code. For dynamic case you should be able to generate the tree from string or IO. Binding can be identified by $$bindingName or x where x is the xth interpolation. You can replace the above convention with anything that works.

Is it possible to have this type of functionality perhaps starting with paradise plugin as it is faster to get it into the plugin? I can really use the above on something I am working on. Perhaps version targeted at 2.11.5? 

This is to deal with cases:
1. You do not know the types at compile time or the types to be used are path dependent (but not Scala path dependent types) - something similar to dependency injection
2. You do not know variable bindings at compile time or is path dependent
3. The code to be executed is not known at compile time or is path dependent

**Comment by xeno-by** [comment]
https://groups.google.com/forum/#!topic/scalameta/MNV-GinD6XY

**Comment by sirinath** [comment]
Any feedback on this? If this can make it as a feature soon it can be really useful for me.

**Comment by xeno-by** [comment]
Thanks for bringing this up! Today and tomorrow I'm really overwhelmed, so I just triaged all my email and went on to hack something very urgent, but I'll try to take a look during the weekend.

**Comment by sirinath** [comment]
Also another thing to consider is nesting. So the parameter can be a map.

**Comment by xeno-by** [comment]
Am I right in thinking that `q".... var a : $$t = ...".bindDynamic("t", Tree.from("MyType"))` is equivalent to: `val t = Tree.from(something); q".... var a: $t = ..."`?

**Comment by sirinath** [comment]
Yes.
1. But you can inject `t` at a later point. `val t1 = Tree.from(something1); val t2 = Tree.from(something2); val qq = q".... var a: $$t = ..."; ...; var qq1 = qq.bindDynamic ("t", t1); ...; var qq2 = qq.bindDynamic ("t", t2); ...`
2. You should be able to load a tree easily from string or IO

**Comment by xeno-by** [comment]
What's `bindStatic` then?

**Comment by sirinath** [comment]
Do it at compile time. Having two may have better optimisation / type checking option for static but you can have just `bind`. Though I am using qq for example this operation is on a tree.

Any part you plugin should be know at compile time. Dynamic you have some runtime penalty to generate the tree and do runtime manipulations and code generation. Also dynamic can return Try as we do not know whether what you are trying to inject is valid.

**Comment by xeno-by** [comment]
How is `bindStatic` different from splicing?

**Comment by sirinath** [comment]
It is more or less the same but flexible with out some of the limitations as mentioned in the docs. But again with splicing you cannot change the list and have the qq's bindings change?

You can consider this to be a more flexible and powerful splicing mechanism. You have a set of place holders which you can change. The similarity with splicing will be if you need to change many place holders a splicing like mechanism can bee used. Also note any sub tree injected to a place holder can have other place holders which can be injected with other place holders which have other place holders and so on. This way you can have a code template which you can expand.

var l = List( ... ) // point 1
var q = q"f(..$l)"

l = List( ... ) // point 2
// What is q now? Does the splicing expand to content of list in point 1 or 2? Say I pass the tree to another function of return it, how can I change the binds in `l` and generate a new tree as l is no longer in scope? If q keeps changing then l is changed this is dangerous.

**Comment by xeno-by** [comment]
What limitations are you referring to?

**Comment by sirinath** [comment]
Limitation is splicing in the current form:
1. Splicing is better suited to function arguments in the current for. Expansions like: `q"var v: $$a = $$b($$c); v.f($$d)"` are not possible. `$$x` refers to a place holder.
2. The bindings are immediate and cannot be delayed or made at different point in code. E.g. `val q = q" ...; f(..$a); "` at this point I do not exactly know what parameters which should go into `a` or we know only some but not all of the parameters then splicing cannot be used.
3. Cannot easily regenerate a new tree by replacing existing bindings. E.g. `var a ...; var b ...; val q = q" ...; f(..$a); "` we are now struck with the binding for `$a`. I cannot change it to `b` or if I assign a new list to `a` or even if I modify `a` (even if this was possible if a goes out of scope I am again struck with `a`).

**Comment by sirinath** [comment]
It is immaterial what you call this feature may it be splicing or something else. What is needed:
- Support delayed binding, code injection of place holders in qq and trees. What is injected can either be know at compile time (but some other location in the code than where the qq / tree was defined) or only know at run time.
- Ability generate a new tree by rebinding  place holders using the existing tree as a template. A way to identify points in the tree which a new tree and be injected to create a new tree.
- Handle nested templates. If a tree has multiple place holders which are bound to trees which them selves contain place holders, then how to uniquely identify the nested place holders and provide binds. 

Dependency injection will not be this popular if delayed wiring / binding is not useful. This also will be very useful in macros and QQs.

**Comment by xeno-by** [comment]
Do you think this could be implemented as a library?

**Comment by sirinath** [comment]
Best place to have it is as part of `Tree`. If you try as a lib you have to then have your own tree. Duplication of work and maybe painful. Also you should have better Tree composition and manipulation APIs this can be a simple start in this direction.

**Comment by xeno-by** [comment]
Can't this be a series of extension methods?

**Comment by sirinath** [comment]
Possibly by before that you have to introduce a place holder to the Tree to which you can attach another tree.

Also introduce some schematics to have place holders in QQs and reify.

**Comment by xeno-by** [comment]
I think this is out of scope for this project.
