### ISSUE TITLE
Optimisation and reduction

### ISSUE THREAD

**Issue by sirinath** [scalamacros/paradise#59]
This is a nice to have feature. Is it possible to have a tree reducer where you can optimise any tree to the most efficient usage.

``` scala
var t1 = q" ... " reduce ruleSet
```

In combination with binds:

``` scala
var t2 = (q" ... ").bindDynamic(0, q" ... ").reduce(ruleSet)

var t3 = (q" ... ").bindDynamic(0, q" ... ").reduce // Default reduction, optimisation rule set
```

May be the easiest would be get it into paradise and then into Scala Meta.

**Comment by xeno-by** [comment]
https://groups.google.com/forum/#!topic/scalameta/j4W5eg-cnus

**Comment by xeno-by** [comment]
What does `bindDynamic` mean? upd. Okay, probably that refers to something introduced in https://github.com/scalamacros/paradise/issues/58.

**Comment by sirinath** [comment]
I meant this for part of the qq which is supplied at runtime. The qq is used like a template where the template elements can be filled in later.

**Comment by xeno-by** [comment]
I think this is out of scope for this project.
