### ISSUE TITLE
support macro bundles for macro annotations

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scalamacros/paradise#62]
it looks like macro bundles 
http://docs.scala-lang.org/overviews/macros/bundles.html

can not be used with macro annotations
http://docs.scala-lang.org/overviews/macros/annotations.html

due to current shape of macro annotation

**Comment by xeno-by** [comment]
Umm, you're saying that you can't implement `macroTransform` in a macro bundle?

**Comment by Andrei-Pozolotin** [comment]
tried again and it works now. no more macros on Saturday night :-)
