### ISSUE TITLE
AOP Like Support | Tree Query

### ISSUE THREAD

**Issue by sirinath** [scalamacros/paradise#63]
Ability to 
1. query language constructs in a Tree and insert place holders to which you can inject code.
2. replace parts of the the tree with place holders.

This depends on this https://github.com/scalamacros/paradise/issues/58 being in place.

**Comment by xeno-by** [comment]
Could you give a few examples?

**Comment by sirinath** [comment]
Point just after method, point before return, point at where a variable is declared, etc.

**Comment by sirinath** [comment]
In short this will be like a programmable find and replace or find and insert. You find certain code constructs and insert, update or delete elements to get your new tree.

**Comment by xeno-by** [comment]
I think this is out of scope for this project.
