### ISSUE TITLE
Possible 2.12 regression

### ISSUE THREAD

**Issue by ghost** [scalamacros/paradise#85]
Ref https://issues.scala-lang.org/browse/SI-9923

Looks like https://github.com/scalamacros/paradise/commit/cd61e7a163049d97132d76627d57399002e2e5d4 never made it to 2.12.

**Comment by ghost** [comment]
Also looks like https://github.com/scalamacros/paradise/commit/c14c634923313dd03f4f483be3d7782a9b56de0e missed the cut, too

**Comment by xeno-by** [comment]
Thank you for debugging! I'll get to this first thing when I come back from vacation.

**Comment by ghost** [comment]
You'll have to thank @som-snytt for all the debugging, I'm just the messenger,

Enjoy your hols :smile:

**Comment by xeno-by** [comment]
Fixed in paradise 2.1.0 for 2.12.0-RC2.

**Comment by SethTisue** [comment]
your dependencies (ScalaTest and ScalaCheck) have now been published for 2.12.0-RC2.

**Comment by xeno-by** [comment]
Released paradise 2.1.0 for 2.12.0-RC2: https://oss.sonatype.org/content/repositories/releases/org/scalamacros/paradise_2.12.0-RC2/.
