### ISSUE TITLE
Release for 2.12.0

### ISSUE THREAD

**Issue by etorreborre** [scalamacros/paradise#87]
Can we have a release for Scala 2.12 final please?

[Shapeless #651](https://github.com/milessabin/shapeless/issues/651) relies on it. Thanks!

**Comment by xeno-by** [comment]
I'm blocked by https://github.com/scalatest/scalatest/issues/989. Otherwise, I'm ready to publish.

**Comment by xeno-by** [comment]
https://oss.sonatype.org/content/repositories/releases/org/scalamacros/paradise_2.12.0/
