### ISSUE TITLE
Compiler error when a macro-annotated class has a non-macro annotation and a companion object defined above it

### ISSUE THREAD

**Issue by xeno-by** [scalamacros/paradise#9]
```
import scala.reflect.macros.Context
import scala.language.experimental.macros
import scala.annotation.StaticAnnotation

object identityMacro {
  def impl(c: Context)(annottees: c.Expr[Any]*): c.Expr[Any] = {
    import c.universe._
    c.Expr[Any](Block(annottees.map(_.tree).toList, Literal(Constant(()))))
  }
}

class identity extends StaticAnnotation {
  def macroTransform(annottees: Any*) = macro identityMacro.impl
}
```

```
class problem extends scala.annotation.Annotation
object Example
@identity @problem class Example(val foo: Int)
```

```
17:27 ~/Projects/Paradise2103/sandbox/src/main/scala (2.10.3)$ ss
Test.scala:3: error: constructor definition not allowed here
@identity @problem class Example(val foo: Int)
^
Test.scala:3: error: foo is already defined as value foo
@identity @problem class Example(val foo: Int)
                                     ^
Test.scala:3: error: self constructor arguments cannot reference unconstructed `this`
@identity @problem class Example(val foo: Int)
                                ^
three errors found
```

**Comment by xeno-by** [comment]
As a workaround, move the definition of the companion object below the annotated class, and the error will go away.

**Comment by xeno-by** [comment]
Looks very related to #10

**Comment by xeno-by** [comment]
Actually it's only partially related. After I fixed #9, the "constructor definition not allowed here" is still there, although "foo is already defined as value foo" and "self constructor arguments cannot reference unconstructed `this`" are gone.

**Comment by xeno-by** [comment]
Fixed in https://scala-webapps.epfl.ch/jenkins/view/misc/job/macro-paradise-nightly-2.10.3/154/console

**Comment by iamroylin** [comment]
Hey, I am having the exact same problem in scala 2.10 using play framework 2.2.2

The problem only occurs if i use the dist or stage command, and never happens when i run the application, which makes it impossible for me to deploy.

I see that you have fixed this for 2.11.0-M8, however play framework is still using 2.10.4

Im quite new to Scala, are you able to point me in the right direction?

Thanks heaps,
Roy

**Comment by xeno-by** [comment]
What version of paradise are you using? Could you try `addCompilerPlugin("org.scalamacros" % "paradise" % "2.0.0-M7" cross CrossVersion.full)`?

**Comment by iamroylin** [comment]
Thanks Eugene,

That is the version I am using.

I just created a minimalist project, and I didn't encounter the same problem. So I must be doing something wrong elsewhere =/
