### ISSUE TITLE
Release for 2.13.0-M1

### ISSUE THREAD

**Issue by milessabin** [scalamacros/paradise#97]
My corner of the ecosystem can't move on to 2.13.x without it ...

**Comment by xeno-by** [comment]
I had a suspicion I forgot about something in this flurry of 2.11.x and 2.12.x releases...

I'll take a stab at producing a 2.13.x build of paradise after my ScalaDays Chicago talk. I may have time to do that before, but can't promise that, because the talk isn't fully ready yet.

**Comment by xeno-by** [comment]
Is there a 2.13.0-M1 based build of scalatest? /cc @bvenners @cheeseng

**Comment by xeno-by** [comment]
I've just migrated from scalatest to junit: https://github.com/scalamacros/paradise/commit/fe17d2651310bedc30c9a3d15e2fbad8c0818935. This should make future releases much easier :)

**Comment by xeno-by** [comment]
https://oss.sonatype.org/content/repositories/releases/org/scalamacros/paradise_2.13.0-M1/

**Comment by bvenners** [comment]
Sorry Eugene, I was on a plane when you asked and Chee Seng was not online yet. Unfortunately I didn't know about the 2.13.0-M1 release. I asked Chee Seng to do a build today.

**Comment by cheeseng** [comment]
@xeno-by @bvenners Sorry Eugene, I just published 3.0.3 for Scala 2.13.0-M1, FYI scala-js build is not available yet as it seems we need to wait for 0.6.16: 

https://github.com/scala-js/scala-js/issues/2898

**Comment by xeno-by** [comment]
Thank you, @bvenners @cheeseng!
